// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMpcv1DkxAune_EsYR-sO8obxzVvTkoc',
    appId: '1:366312963654:web:2f8dc01720ec1508ad9447',
    messagingSenderId: '366312963654',
    projectId: 'spotify-clone-alfatist',
    authDomain: 'spotify-clone-alfatist.firebaseapp.com',
    storageBucket: 'spotify-clone-alfatist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmJ9N_gEWTmJtslWsf-4ah_2Nt9fgVd0',
    appId: '1:366312963654:android:5e8fa74e3758b600ad9447',
    messagingSenderId: '366312963654',
    projectId: 'spotify-clone-alfatist',
    storageBucket: 'spotify-clone-alfatist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72AmYdR-b3gRFftRM70lz1APngWuadZ4',
    appId: '1:366312963654:ios:1c153ff42a1dce24ad9447',
    messagingSenderId: '366312963654',
    projectId: 'spotify-clone-alfatist',
    storageBucket: 'spotify-clone-alfatist.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC72AmYdR-b3gRFftRM70lz1APngWuadZ4',
    appId: '1:366312963654:ios:1c153ff42a1dce24ad9447',
    messagingSenderId: '366312963654',
    projectId: 'spotify-clone-alfatist',
    storageBucket: 'spotify-clone-alfatist.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMpcv1DkxAune_EsYR-sO8obxzVvTkoc',
    appId: '1:366312963654:web:c2e1bd08b1944c14ad9447',
    messagingSenderId: '366312963654',
    projectId: 'spotify-clone-alfatist',
    authDomain: 'spotify-clone-alfatist.firebaseapp.com',
    storageBucket: 'spotify-clone-alfatist.firebasestorage.app',
  );
}
